name = "tranquilapi"
main = "src/index.ts"
compatibility_date = "2023-05-18"

workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[[r2_buckets]]
binding = 'bucket'
bucket_name = 'tranquil'

[[d1_databases]]
binding = 'database'
database_name = 'tranquil'
database_id = '671954cf-2942-44a1-80e6-e943cece374b'